### ISSUE TITLE
Can I use docker-ovs image with docker-compose as switch without using pipework? 

### ISSUE THREAD

**Issue by giper45** [socketplane/docker-ovs#21]
Hi,
is it possible to use docker-compose / docker feature to use the following image as a switch of containers belonging to the same network? 

For example, I have the following docker-compose: 
```
version: '2'
services:
  dspdnsenum.lab:
    image: 'cosmicq/docker-bind:latest'
    stdin_open: true
    tty: true
    networks:
      public_dnsenum:
        ipv4_address: 193.21.1.2
    environment:
      - PASS=newpass
    volumes:
      - './var-lib-bind:/var/lib/bind'
      - './bind:/etc/bind'
      - './webmin:/etc/webmin'
  server:
    image: 'cosmicq/docker-bind:latest'
    stdin_open: true
    tty: true
    networks:
      public_dnsenum:
        ipv4_address: 193.21.1.3
    environment:
      - PASS=newpass
    volumes:
      - './webmin-slave:/etc/webmin'
      - './bind-slave:/etc/bind'
      - './var-lib-bind-slave:/var/lib/bind'
networks:
  public_dnsenum:
    ipam:
      config:
        - subnet: 193.21.1.1/24


```

I have a network with 2 services, it would very useful for my scenario to let all network pass through a docker-ovs image, so I would be able to make traffic analysis of all traffic. 
I am thinking about best ways integrate switch / router support in my project, [DSP](https://github.com/giper45/DockerSecurityPlayground).
It would be very useful to integrate natively your image in my environment. 
Thanks very much in advance,
GP
